#! /usr/bin/env node
var data = require('./setup.json');
var fs = require('fs');
if (process.argv.length > 3) {
    data.osc = { 'ip': process.argv[2], 'port': process.argv[3] };
} else if (process.argv.length > 2) {
    data.osc = { 'ip': process.argv[2], 'port': 8000 };
}
else {
    console.error('bad format, should be : set-osc [\'destip\'] [destport]');
    data.osc = null;
}
fs.writeFile('setup.json', JSON.stringify(data), function (e) { });